

export enum ElementType {
  PRIMITIVE = 'PRIMITIVE',
  SHAPE = 'SHAPE',
  DOOR = 'DOOR',
  WINDOW = 'WINDOW',
  WALL = 'WALL',
  SLAB = 'SLAB',
  STAIR = 'STAIR',
  SPACECONTAINER = 'SPACECONTAINER',
  BOARD = 'BOARD',
  PAPER = 'PAPER',
}

export enum DoorType {
  GLASS = 'GLASS',
  WOOD = 'WOOD',
  DOUBLEDOOR = 'DOUBLEDOOR',
  SLIDING = 'SLIDING',
  FOLDING = 'FOLDING',
  DOUBLEACTION = 'DOUBLEACTION',
  OTHER = 'OTHER',
}

export enum WindowType {
  GLASS = 'GLASS',
  WOOD = 'WOOD',
  SLIDING = 'SLIDING',
  CASEMENT = 'CASEMENT',
  AWNING = 'AWNING',
  FIXED = 'FIXED',
  OTHER = 'OTHER',
}
